//! Stopwords for German, English, and HTML/technical terms
//!
//! Common words that should be filtered out during keyword extraction.
//! Includes built-in stopwords and user-defined stopwords from database.

use rusqlite::Connection;
use std::collections::HashSet;
use std::sync::LazyLock;

/// Combined German, English, HTML/technical, and news stopwords
pub static STOPWORDS: LazyLock<HashSet<&'static str>> = LazyLock::new(|| {
    let mut words = HashSet::new();

    // German stopwords
    for word in GERMAN_STOPWORDS {
        words.insert(*word);
    }

    // English stopwords
    for word in ENGLISH_STOPWORDS {
        words.insert(*word);
    }

    // HTML/technical stopwords
    for word in HTML_STOPWORDS {
        words.insert(*word);
    }

    // News-specific stopwords
    for word in NEWS_STOPWORDS {
        words.insert(*word);
    }

    words
});

static GERMAN_STOPWORDS: &[&str] = &[
    // ========================================
    // ARTICLES
    // ========================================
    "der",
    "die",
    "das",
    "den",
    "dem",
    "des",
    "ein",
    "eine",
    "einer",
    "einem",
    "einen",
    "eines",
    // ========================================
    // PRONOUNS (all cases and forms)
    // ========================================
    "ich",
    "du",
    "er",
    "sie",
    "es",
    "wir",
    "ihr",
    "mich",
    "dich",
    "sich",
    "uns",
    "euch",
    "mir",
    "dir",
    "ihm",
    "ihnen",
    "mein",
    "dein",
    "sein",
    "unser",
    "euer",
    "meiner",
    "deiner",
    "seiner",
    "unserer",
    "eurer",
    "meinen",
    "deinen",
    "seinen",
    "meine",
    "deine",
    "seine",
    "unsere",
    "eure",
    "meines",
    "deines",
    "seines",
    "meinem",
    "deinem",
    "seinem",
    "unserem",
    "eurem",
    "unseren",
    "euren",
    "ihre",
    "ihrer",
    "ihren",
    "ihrem",
    "ihres",
    "dessen",
    "deren",
    "derer",
    "man",
    "jemand",
    "niemand",
    "etwas",
    "nichts",
    "alles",
    "wer",
    "was",
    // ========================================
    // PREPOSITIONS
    // ========================================
    "in",
    "an",
    "auf",
    "aus",
    "bei",
    "mit",
    "nach",
    "über",
    "unter",
    "vor",
    "zwischen",
    "durch",
    "für",
    "gegen",
    "ohne",
    "um",
    "von",
    "zu",
    "bis",
    "seit",
    "während",
    "wegen",
    "trotz",
    "statt",
    "anstatt",
    "außer",
    "binnen",
    "dank",
    "entlang",
    "gegenüber",
    "gemäß",
    "infolge",
    "inmitten",
    "innerhalb",
    "jenseits",
    "kraft",
    "längs",
    "laut",
    "mangels",
    "mittels",
    "oberhalb",
    "seitens",
    "unterhalb",
    "unweit",
    "vermöge",
    "zufolge",
    "zugunsten",
    "zuliebe",
    "zwecks",
    // Contracted forms
    "im",
    "am",
    "ans",
    "aufs",
    "beim",
    "durchs",
    "fürs",
    "hinters",
    "ins",
    "übers",
    "ums",
    "unters",
    "vom",
    "vors",
    "zum",
    "zur",
    // ========================================
    // CONJUNCTIONS
    // ========================================
    "und",
    "oder",
    "aber",
    "denn",
    "weil",
    "wenn",
    "als",
    "ob",
    "dass",
    "damit",
    "obwohl",
    "sondern",
    "sowohl",
    "weder",
    "noch",
    "entweder",
    "bevor",
    "nachdem",
    "sobald",
    "solange",
    "sofern",
    "soweit",
    "falls",
    "obgleich",
    "obschon",
    "obzwar",
    "wenngleich",
    "während",
    "indem",
    "wobei",
    "weshalb",
    "weswegen",
    "worauf",
    "woraufhin",
    "wohingegen",
    "zumal",
    "da",
    // ========================================
    // AUXILIARY & MODAL VERBS (all forms)
    // ========================================
    // sein
    "sein",
    "bin",
    "bist",
    "ist",
    "sind",
    "seid",
    "war",
    "warst",
    "waren",
    "wart",
    "gewesen",
    "sei",
    "seist",
    "seien",
    "seiet",
    "wäre",
    "wärst",
    "wären",
    "wäret",
    // haben
    "haben",
    "habe",
    "hast",
    "hat",
    "habt",
    "hatte",
    "hattest",
    "hatten",
    "hattet",
    "gehabt",
    "hätte",
    "hättest",
    "hätten",
    "hättet",
    // werden
    "werden",
    "werde",
    "wirst",
    "wird",
    "werdet",
    "wurde",
    "wurdest",
    "wurden",
    "wurdet",
    "geworden",
    "worden",
    "würde",
    "würdest",
    "würden",
    "würdet",
    // können
    "können",
    "kann",
    "kannst",
    "könnt",
    "konnte",
    "konntest",
    "konnten",
    "konntet",
    "gekonnt",
    "könnte",
    "könntest",
    "könnten",
    "könntet",
    // müssen
    "müssen",
    "muss",
    "musst",
    "müsst",
    "musste",
    "musstest",
    "mussten",
    "musstet",
    "gemusst",
    "müsste",
    "müsstest",
    "müssten",
    "müsstet",
    // sollen
    "sollen",
    "soll",
    "sollst",
    "sollt",
    "sollte",
    "solltest",
    "sollten",
    "solltet",
    "gesollt",
    // wollen
    "wollen",
    "will",
    "willst",
    "wollt",
    "wollte",
    "wolltest",
    "wollten",
    "wolltet",
    "gewollt",
    // dürfen
    "dürfen",
    "darf",
    "darfst",
    "dürft",
    "durfte",
    "durftest",
    "durften",
    "durftet",
    "gedurft",
    "dürfte",
    "dürftest",
    "dürften",
    "dürftet",
    // mögen
    "mögen",
    "mag",
    "magst",
    "mögt",
    "mochte",
    "mochtest",
    "mochten",
    "mochtet",
    "gemocht",
    "möchte",
    "möchtest",
    "möchten",
    "möchtet",
    // lassen
    "lassen",
    "lasse",
    "lässt",
    "lasst",
    "ließ",
    "ließt",
    "ließen",
    "gelassen",
    // ========================================
    // COMMON VERBS (all forms) - NEWS CRITICAL
    // ========================================
    // sagen (say)
    "sagen",
    "sage",
    "sagst",
    "sagt",
    "sagte",
    "sagtest",
    "sagten",
    "sagtet",
    "gesagt",
    // geben (give)
    "geben",
    "gebe",
    "gibst",
    "gibt",
    "gebt",
    "gab",
    "gabst",
    "gaben",
    "gabt",
    "gegeben",
    // gehen (go)
    "gehen",
    "gehe",
    "gehst",
    "geht",
    "ging",
    "gingst",
    "gingen",
    "gingt",
    "gegangen",
    // kommen (come)
    "kommen",
    "komme",
    "kommst",
    "kommt",
    "kam",
    "kamst",
    "kamen",
    "kamt",
    "gekommen",
    // machen (make/do)
    "machen",
    "mache",
    "machst",
    "macht",
    "machte",
    "machtest",
    "machten",
    "machtet",
    "gemacht",
    // nehmen (take)
    "nehmen",
    "nehme",
    "nimmst",
    "nimmt",
    "nehmt",
    "nahm",
    "nahmst",
    "nahmen",
    "nahmt",
    "genommen",
    // stehen (stand)
    "stehen",
    "stehe",
    "stehst",
    "steht",
    "stand",
    "standst",
    "standen",
    "standet",
    "gestanden",
    // bleiben (stay)
    "bleiben",
    "bleibe",
    "bleibst",
    "bleibt",
    "blieb",
    "bliebst",
    "blieben",
    "bliebt",
    "geblieben",
    // heißen (be called)
    "heißen",
    "heiße",
    "heißt",
    "hieß",
    "hießt",
    "hießen",
    "geheißen",
    // liegen (lie)
    "liegen",
    "liege",
    "liegst",
    "liegt",
    "lag",
    "lagst",
    "lagen",
    "lagt",
    "gelegen",
    // sehen (see)
    "sehen",
    "sehe",
    "siehst",
    "sieht",
    "seht",
    "sah",
    "sahst",
    "sahen",
    "saht",
    "gesehen",
    // wissen (know)
    "wissen",
    "weiß",
    "weißt",
    "wisst",
    "wusste",
    "wusstest",
    "wussten",
    "wusstet",
    "gewusst",
    // zeigen (show)
    "zeigen",
    "zeige",
    "zeigst",
    "zeigt",
    "zeigte",
    "zeigtest",
    "zeigten",
    "zeigtet",
    "gezeigt",
    // führen (lead)
    "führen",
    "führe",
    "führst",
    "führt",
    "führte",
    "führtest",
    "führten",
    "führtet",
    "geführt",
    // halten (hold)
    "halten",
    "halte",
    "hältst",
    "hält",
    "haltet",
    "hielt",
    "hieltest",
    "hielten",
    "hieltet",
    "gehalten",
    // bringen (bring)
    "bringen",
    "bringe",
    "bringst",
    "bringt",
    "brachte",
    "brachtest",
    "brachten",
    "brachtet",
    "gebracht",
    // finden (find)
    "finden",
    "finde",
    "findest",
    "findet",
    "fand",
    "fandst",
    "fanden",
    "fandet",
    "gefunden",
    // tragen (carry)
    "tragen",
    "trage",
    "trägst",
    "trägt",
    "tragt",
    "trug",
    "trugst",
    "trugen",
    "trugt",
    "getragen",
    // setzen (set)
    "setzen",
    "setze",
    "setzt",
    "setzte",
    "setztest",
    "setzten",
    "setztet",
    "gesetzt",
    // sprechen (speak)
    "sprechen",
    "spreche",
    "sprichst",
    "spricht",
    "sprecht",
    "sprach",
    "sprachst",
    "sprachen",
    "spracht",
    "gesprochen",
    // schreiben (write)
    "schreiben",
    "schreibe",
    "schreibst",
    "schreibt",
    "schrieb",
    "schriebst",
    "schrieben",
    "schriebt",
    "geschrieben",
    // lesen (read)
    "lesen",
    "lese",
    "liest",
    "lest",
    "las",
    "last",
    "lasen",
    "gelesen",
    // erklären (explain)
    "erklären",
    "erkläre",
    "erklärst",
    "erklärt",
    "erklärte",
    "erklärtest",
    "erklärten",
    "erklärtet",
    // berichten (report)
    "berichten",
    "berichte",
    "berichtest",
    "berichtet",
    "berichtete",
    "berichtetest",
    "berichteten",
    "berichtetet",
    // meinen (mean/think)
    "meinen",
    "meine",
    "meinst",
    "meint",
    "meinte",
    "meintest",
    "meinten",
    "meintet",
    "gemeint",
    // glauben (believe)
    "glauben",
    "glaube",
    "glaubst",
    "glaubt",
    "glaubte",
    "glaubtest",
    "glaubten",
    "glaubtet",
    "geglaubt",
    // denken (think)
    "denken",
    "denke",
    "denkst",
    "denkt",
    "dachte",
    "dachtest",
    "dachten",
    "dachtet",
    "gedacht",
    // scheinen (seem)
    "scheinen",
    "scheine",
    "scheinst",
    "scheint",
    "schien",
    "schienst",
    "schienen",
    "schient",
    "geschienen",
    // beginnen (begin)
    "beginnen",
    "beginne",
    "beginnst",
    "beginnt",
    "begann",
    "begannst",
    "begannen",
    "begannt",
    "begonnen",
    // enden (end)
    "enden",
    "ende",
    "endest",
    "endet",
    "endete",
    "endetest",
    "endeten",
    "endetet",
    "geendet",
    // folgen (follow)
    "folgen",
    "folge",
    "folgst",
    "folgt",
    "folgte",
    "folgtest",
    "folgten",
    "folgtet",
    "gefolgt",
    // betreffen (concern)
    "betreffen",
    "betreffe",
    "betriffst",
    "betrifft",
    "betraft",
    "betraf",
    "betrafen",
    "betroffen",
    // erwarten (expect)
    "erwarten",
    "erwarte",
    "erwartest",
    "erwartet",
    "erwartete",
    "erwartetest",
    "erwarteten",
    "erwartet",
    // fordern (demand)
    "fordern",
    "fordere",
    "forderst",
    "fordert",
    "forderte",
    "fordertest",
    "forderten",
    "gefordert",
    // warnen (warn)
    "warnen",
    "warne",
    "warnst",
    "warnt",
    "warnte",
    "warntest",
    "warnten",
    "gewarnt",
    // bestätigen (confirm)
    "bestätigen",
    "bestätige",
    "bestätigst",
    "bestätigt",
    "bestätigte",
    "bestätigtest",
    "bestätigten",
    "bestätigt",
    // mitteilen (inform)
    "mitteilen",
    "teile",
    "teilst",
    "teilt",
    "teilte",
    "teiltest",
    "teilten",
    "mitgeteilt",
    // hinweisen (point out)
    "hinweisen",
    "hinweise",
    "hinweist",
    "wies",
    "wiesen",
    "hingewiesen",
    // bekannt (known)
    "bekannt",
    "bekanntgeben",
    "bekanntgegeben",
    // ========================================
    // ADVERBS
    // ========================================
    "auch",
    "noch",
    "schon",
    "nur",
    "sehr",
    "so",
    "wie",
    "hier",
    "dort",
    "da",
    "dann",
    "wann",
    "wo",
    "warum",
    "weshalb",
    "wieso",
    "jetzt",
    "nun",
    "immer",
    "nie",
    "oft",
    "manchmal",
    "vielleicht",
    "bestimmt",
    "sicher",
    "etwa",
    "ungefähr",
    "fast",
    "ganz",
    "gar",
    "ziemlich",
    "recht",
    "eher",
    "mehr",
    "weniger",
    "meist",
    "mindestens",
    "wieder",
    "bereits",
    "bisher",
    "künftig",
    "insgesamt",
    "insbesondere",
    "außerdem",
    "zudem",
    "dabei",
    "dafür",
    "dagegen",
    "danach",
    "davor",
    "dazu",
    "darauf",
    "darin",
    "darüber",
    "darunter",
    "davon",
    "damit",
    "daran",
    "darum",
    "deshalb",
    "deswegen",
    "daher",
    "dadurch",
    "dennoch",
    "trotzdem",
    "allerdings",
    "jedoch",
    "freilich",
    "jedenfalls",
    "übrigens",
    "nämlich",
    "eigentlich",
    "überhaupt",
    "sozusagen",
    "gleichsam",
    "gewissermaßen",
    "offenbar",
    "anscheinend",
    "vermutlich",
    "wahrscheinlich",
    "möglicherweise",
    "eventuell",
    "tatsächlich",
    "wirklich",
    "zuletzt",
    "zunächst",
    "zuerst",
    "schließlich",
    "endlich",
    "letztlich",
    "letztendlich",
    "inzwischen",
    "mittlerweile",
    "unterdessen",
    "derweil",
    "derzeit",
    "zurzeit",
    "sofort",
    "gleich",
    "bald",
    "später",
    "früher",
    "vorher",
    "nachher",
    "daneben",
    "daraufhin",
    "dementsprechend",
    "demzufolge",
    "folglich",
    "somit",
    "demnach",
    "hierzulande",
    "anderorts",
    "anderswo",
    "überall",
    "nirgends",
    "irgendwo",
    // ========================================
    // ADJECTIVES (common forms)
    // ========================================
    "andere",
    "anderer",
    "anderes",
    "anderen",
    "anderem",
    "alle",
    "aller",
    "alles",
    "allem",
    "viel",
    "viele",
    "vieler",
    "vielen",
    "vielem",
    "wenig",
    "wenige",
    "weniger",
    "einige",
    "einiger",
    "einiges",
    "einigen",
    "einigem",
    "manche",
    "mancher",
    "manches",
    "jede",
    "jeder",
    "jedes",
    "jeden",
    "jedem",
    "keine",
    "keiner",
    "keines",
    "keinen",
    "keinem",
    "solche",
    "solcher",
    "solches",
    "solchen",
    "solchem",
    "gleiche",
    "gleicher",
    "gleiches",
    "gleichen",
    "gleichem",
    "eigene",
    "eigener",
    "eigenes",
    "eigenen",
    "eigenem",
    "selbe",
    "selber",
    "selbes",
    "selben",
    "selbem",
    "selbst",
    "letzte",
    "letzter",
    "letztes",
    "letzten",
    "letztem",
    "nächste",
    "nächster",
    "nächstes",
    "nächsten",
    "nächstem",
    "erste",
    "erster",
    "erstes",
    "ersten",
    "erstem",
    "zweite",
    "zweiter",
    "zweites",
    "zweiten",
    "zweitem",
    "dritte",
    "dritter",
    "drittes",
    "dritten",
    "drittem",
    "beide",
    "beider",
    "beiden",
    "beidem",
    "beides",
    "weitere",
    "weiterer",
    "weiteres",
    "weiteren",
    "weiterem",
    "neue",
    "neuer",
    "neues",
    "neuen",
    "neuem",
    "alte",
    "alter",
    "altes",
    "alten",
    "altem",
    "große",
    "großer",
    "großes",
    "großen",
    "großem",
    "kleine",
    "kleiner",
    "kleines",
    "kleinen",
    "kleinem",
    "hohe",
    "hoher",
    "hohes",
    "hohen",
    "hohem",
    "lange",
    "langer",
    "langes",
    "langen",
    "langem",
    "kurze",
    "kurzer",
    "kurzes",
    "kurzen",
    "kurzem",
    "gute",
    "guter",
    "gutes",
    "guten",
    "gutem",
    "wichtige",
    "wichtiger",
    "wichtiges",
    "wichtigen",
    "wichtigem",
    "verschiedene",
    "verschiedener",
    "verschiedenes",
    "verschiedenen",
    "verschiedenem",
    "bestimmte",
    "bestimmter",
    "bestimmtes",
    "bestimmten",
    "bestimmtem",
    "gewisse",
    "gewisser",
    "gewisses",
    "gewissen",
    "gewissem",
    "genaue",
    "genauer",
    "genaues",
    "genauen",
    "genauem",
    "richtige",
    "richtiger",
    "richtiges",
    "richtigen",
    "richtigem",
    "falsche",
    "falscher",
    "falsches",
    "falschen",
    "falschem",
    "schlecht",
    "schlechte",
    "schlechter",
    "schlechtes",
    "schlechten",
    "schlechtem",
    // ========================================
    // DEMONSTRATIVES
    // ========================================
    "diese",
    "dieser",
    "dieses",
    "diesen",
    "diesem",
    "jene",
    "jener",
    "jenes",
    "jenen",
    "jenem",
    // ========================================
    // NUMBERS
    // ========================================
    "null",
    "eins",
    "zwei",
    "drei",
    "vier",
    "fünf",
    "sechs",
    "sieben",
    "acht",
    "neun",
    "zehn",
    "elf",
    "zwölf",
    "dreizehn",
    "vierzehn",
    "fünfzehn",
    "sechzehn",
    "siebzehn",
    "achtzehn",
    "neunzehn",
    "zwanzig",
    "dreißig",
    "vierzig",
    "fünfzig",
    "sechzig",
    "siebzig",
    "achtzig",
    "neunzig",
    "hundert",
    "tausend",
    "million",
    "millionen",
    "milliarde",
    "milliarden",
    // ========================================
    // QUESTION WORDS
    // ========================================
    "was",
    "wer",
    "wen",
    "wem",
    "wessen",
    "welche",
    "welcher",
    "welches",
    "welchen",
    "welchem",
    "wieviel",
    "wieviele",
    "wieso",
    "weshalb",
    "weswegen",
    "womit",
    "wofür",
    "wogegen",
    "worüber",
    "worunter",
    "wovon",
    "wovor",
    "wozu",
    "wodurch",
    "woher",
    "wohin",
    // ========================================
    // PARTICLES & FILLERS
    // ========================================
    "nicht",
    "kein",
    "nein",
    "ja",
    "doch",
    "mal",
    "halt",
    "eben",
    "wohl",
    "zwar",
    "bloß",
    "nur",
    "ruhig",
    "schon",
    "etwa",
    "vielleicht",
    "wirklich",
    "eigentlich",
    // ========================================
    // TIME-RELATED
    // ========================================
    "jahr",
    "jahre",
    "jahren",
    "jahres",
    "monat",
    "monate",
    "monaten",
    "monats",
    "woche",
    "wochen",
    "tag",
    "tage",
    "tagen",
    "tages",
    "stunde",
    "stunden",
    "minute",
    "minuten",
    "sekunde",
    "sekunden",
    "zeit",
    "zeiten",
    "ende",
    "anfang",
    "mitte",
    "beginn",
    "heute",
    "gestern",
    "morgen",
    "vorgestern",
    "übermorgen",
    "montag",
    "dienstag",
    "mittwoch",
    "donnerstag",
    "freitag",
    "samstag",
    "sonntag",
    "januar",
    "februar",
    "märz",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "dezember",
    "frühjahr",
    "frühling",
    "sommer",
    "herbst",
    "winter",
    // ========================================
    // GENERIC NOUNS (often meaningless as keywords)
    // ========================================
    "fall",
    "fälle",
    "fällen",
    "grund",
    "gründe",
    "gründen",
    "art",
    "arten",
    "teil",
    "teile",
    "teilen",
    "seite",
    "seiten",
    "platz",
    "plätze",
    "stelle",
    "stellen",
    "punkt",
    "punkte",
    "weg",
    "wege",
    "mal",
    "ort",
    "orte",
    "orten",
    "sache",
    "sachen",
    "ding",
    "dinge",
    "dingen",
    "person",
    "personen",
    "mensch",
    "menschen",
    "leute",
    "leuten",
    "frau",
    "frauen",
    "mann",
    "männer",
    "kind",
    "kinder",
    "kindern",
    "frage",
    "fragen",
    "antwort",
    "antworten",
    "problem",
    "probleme",
    "problemen",
    "lösung",
    "lösungen",
    "möglichkeit",
    "möglichkeiten",
    "chance",
    "chancen",
    "situation",
    "grund",
    "gründe",
    "ursache",
    "ursachen",
    "folge",
    "folgen",
    "auswirkung",
    "auswirkungen",
    "entwicklung",
    "entwicklungen",
    "veränderung",
    "veränderungen",
    "bereich",
    "bereiche",
    "bereichen",
    "ebene",
    "ebenen",
    "rahmen",
    "rahmens",
    "zusammenhang",
    "zusammenhänge",
    "hinblick",
    "bezug",
    "hinsicht",
    "zahl",
    "zahlen",
    "anzahl",
    "menge",
    "mengen",
    "form",
    "formen",
    "weise",
    "art",
    "arten",
    "maßnahme",
    "maßnahmen",
    "schritt",
    "schritte",
    "schritten",
    // ========================================
    // WEB/ARTICLE COMMON WORDS
    // ========================================
    "mehr",
    "lesen",
    "artikel",
    "seite",
    "weitere",
    "weiteren",
    "neuen",
    "neue",
    "neuer",
    "aktuell",
    "aktuelle",
    "aktuellen",
    "aktueller",
    "beitrag",
    "beiträge",
    "inhalt",
    "inhalte",
    "text",
    "texte",
    "link",
    "links",
    "quelle",
    "quellen",
    "video",
    "videos",
    "bild",
    "bilder",
    "foto",
    "fotos",
    "grafik",
    "grafiken",
];

static ENGLISH_STOPWORDS: &[&str] = &[
    // ========================================
    // ARTICLES & DETERMINERS
    // ========================================
    "a",
    "an",
    "the",
    "this",
    "that",
    "these",
    "those",
    "some",
    "any",
    "no",
    "every",
    "each",
    "either",
    "neither",
    "both",
    "all",
    "half",
    "several",
    "few",
    "many",
    "much",
    "most",
    "more",
    "less",
    "least",
    "enough",
    "plenty",
    // ========================================
    // PRONOUNS
    // ========================================
    "i",
    "me",
    "my",
    "myself",
    "mine",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "we",
    "us",
    "our",
    "ours",
    "ourselves",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "who",
    "whom",
    "whose",
    "which",
    "what",
    "that",
    "whoever",
    "whomever",
    "whatever",
    "whichever",
    "someone",
    "somebody",
    "something",
    "somewhere",
    "anyone",
    "anybody",
    "anything",
    "anywhere",
    "everyone",
    "everybody",
    "everything",
    "everywhere",
    "no one",
    "nobody",
    "nothing",
    "nowhere",
    "one",
    "ones",
    "other",
    "others",
    "another",
    // ========================================
    // PREPOSITIONS
    // ========================================
    "in",
    "on",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "out",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "across",
    "along",
    "among",
    "around",
    "behind",
    "beside",
    "besides",
    "beyond",
    "despite",
    "except",
    "inside",
    "near",
    "outside",
    "past",
    "since",
    "toward",
    "towards",
    "upon",
    "within",
    "without",
    "throughout",
    "underneath",
    "via",
    // ========================================
    // CONJUNCTIONS
    // ========================================
    "and",
    "but",
    "or",
    "nor",
    "for",
    "yet",
    "so",
    "if",
    "because",
    "as",
    "until",
    "while",
    "of",
    "although",
    "though",
    "whereas",
    "whether",
    "unless",
    "since",
    "than",
    "when",
    "where",
    "after",
    "before",
    "once",
    "whenever",
    "wherever",
    "while",
    "whilst",
    "provided",
    "supposing",
    "unless",
    "until",
    "lest",
    // ========================================
    // AUXILIARY & MODAL VERBS (all forms)
    // ========================================
    // be
    "be",
    "am",
    "is",
    "are",
    "was",
    "were",
    "been",
    "being",
    // have
    "have",
    "has",
    "had",
    "having",
    // do
    "do",
    "does",
    "did",
    "doing",
    "done",
    // modals
    "can",
    "cannot",
    "could",
    "will",
    "would",
    "shall",
    "should",
    "may",
    "might",
    "must",
    "ought",
    // contractions (without apostrophe)
    "dont",
    "doesnt",
    "didnt",
    "wont",
    "wouldnt",
    "shouldnt",
    "couldnt",
    "cant",
    "isnt",
    "arent",
    "wasnt",
    "werent",
    "hasnt",
    "havent",
    "hadnt",
    "mustnt",
    "ive",
    "youve",
    "weve",
    "theyve",
    "hes",
    "shes",
    "its",
    "whats",
    "thats",
    "whos",
    "heres",
    "theres",
    "wheres",
    "lets",
    "ill",
    "youll",
    "hell",
    "shell",
    "well",
    "theyll",
    "id",
    "youd",
    "hed",
    "shed",
    "wed",
    "theyd",
    // ========================================
    // COMMON VERBS (all forms) - NEWS CRITICAL
    // ========================================
    // say
    "say",
    "says",
    "said",
    "saying",
    // tell
    "tell",
    "tells",
    "told",
    "telling",
    // report
    "report",
    "reports",
    "reported",
    "reporting",
    // announce
    "announce",
    "announces",
    "announced",
    "announcing",
    // claim
    "claim",
    "claims",
    "claimed",
    "claiming",
    // state
    "state",
    "states",
    "stated",
    "stating",
    // confirm
    "confirm",
    "confirms",
    "confirmed",
    "confirming",
    // deny
    "deny",
    "denies",
    "denied",
    "denying",
    // warn
    "warn",
    "warns",
    "warned",
    "warning",
    // reveal
    "reveal",
    "reveals",
    "revealed",
    "revealing",
    // show
    "show",
    "shows",
    "showed",
    "shown",
    "showing",
    // find
    "find",
    "finds",
    "found",
    "finding",
    // note
    "note",
    "notes",
    "noted",
    "noting",
    // add
    "add",
    "adds",
    "added",
    "adding",
    // suggest
    "suggest",
    "suggests",
    "suggested",
    "suggesting",
    // believe
    "believe",
    "believes",
    "believed",
    "believing",
    // think
    "think",
    "thinks",
    "thought",
    "thinking",
    // know
    "know",
    "knows",
    "knew",
    "known",
    "knowing",
    // see
    "see",
    "sees",
    "saw",
    "seen",
    "seeing",
    // go
    "go",
    "goes",
    "went",
    "gone",
    "going",
    // come
    "come",
    "comes",
    "came",
    "coming",
    // get
    "get",
    "gets",
    "got",
    "gotten",
    "getting",
    // make
    "make",
    "makes",
    "made",
    "making",
    // take
    "take",
    "takes",
    "took",
    "taken",
    "taking",
    // give
    "give",
    "gives",
    "gave",
    "given",
    "giving",
    // use
    "use",
    "uses",
    "used",
    "using",
    // want
    "want",
    "wants",
    "wanted",
    "wanting",
    // need
    "need",
    "needs",
    "needed",
    "needing",
    // seem
    "seem",
    "seems",
    "seemed",
    "seeming",
    // appear
    "appear",
    "appears",
    "appeared",
    "appearing",
    // become
    "become",
    "becomes",
    "became",
    "becoming",
    // remain
    "remain",
    "remains",
    "remained",
    "remaining",
    // keep
    "keep",
    "keeps",
    "kept",
    "keeping",
    // let
    "let",
    "lets",
    "letting",
    // begin
    "begin",
    "begins",
    "began",
    "begun",
    "beginning",
    // start
    "start",
    "starts",
    "started",
    "starting",
    // call
    "call",
    "calls",
    "called",
    "calling",
    // ask
    "ask",
    "asks",
    "asked",
    "asking",
    // seek
    "seek",
    "seeks",
    "sought",
    "seeking",
    // plan
    "plan",
    "plans",
    "planned",
    "planning",
    // look
    "look",
    "looks",
    "looked",
    "looking",
    // feel
    "feel",
    "feels",
    "felt",
    "feeling",
    // try
    "try",
    "tries",
    "tried",
    "trying",
    // leave
    "leave",
    "leaves",
    "left",
    "leaving",
    // put
    "put",
    "puts",
    "putting",
    // mean
    "mean",
    "means",
    "meant",
    "meaning",
    // turn
    "turn",
    "turns",
    "turned",
    "turning",
    // move
    "move",
    "moves",
    "moved",
    "moving",
    // continue
    "continue",
    "continues",
    "continued",
    "continuing",
    // provide
    "provide",
    "provides",
    "provided",
    "providing",
    // help
    "help",
    "helps",
    "helped",
    "helping",
    // set
    "set",
    "sets",
    "setting",
    // run
    "run",
    "runs",
    "ran",
    "running",
    // hold
    "hold",
    "holds",
    "held",
    "holding",
    // bring
    "bring",
    "brings",
    "brought",
    "bringing",
    // happen
    "happen",
    "happens",
    "happened",
    "happening",
    // write
    "write",
    "writes",
    "wrote",
    "written",
    "writing",
    // read (verb)
    "read",
    "reads",
    "reading",
    // play
    "play",
    "plays",
    "played",
    "playing",
    // stand
    "stand",
    "stands",
    "stood",
    "standing",
    // lose
    "lose",
    "loses",
    "lost",
    "losing",
    // win
    "win",
    "wins",
    "won",
    "winning",
    // pay
    "pay",
    "pays",
    "paid",
    "paying",
    // meet
    "meet",
    "meets",
    "met",
    "meeting",
    // include
    "include",
    "includes",
    "included",
    "including",
    // expect
    "expect",
    "expects",
    "expected",
    "expecting",
    // follow
    "follow",
    "follows",
    "followed",
    "following",
    // ========================================
    // ADVERBS
    // ========================================
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "now",
    "then",
    "always",
    "never",
    "often",
    "sometimes",
    "usually",
    "already",
    "still",
    "yet",
    "ever",
    "just",
    "only",
    "even",
    "also",
    "too",
    "very",
    "really",
    "quite",
    "rather",
    "fairly",
    "almost",
    "nearly",
    "hardly",
    "barely",
    "scarcely",
    "perhaps",
    "maybe",
    "probably",
    "possibly",
    "certainly",
    "definitely",
    "actually",
    "basically",
    "essentially",
    "generally",
    "specifically",
    "particularly",
    "especially",
    "mainly",
    "mostly",
    "largely",
    "partly",
    "completely",
    "entirely",
    "totally",
    "absolutely",
    "perfectly",
    "exactly",
    "precisely",
    "approximately",
    "roughly",
    "soon",
    "later",
    "early",
    "late",
    "recently",
    "currently",
    "previously",
    "eventually",
    "finally",
    "ultimately",
    "immediately",
    "suddenly",
    "gradually",
    "slowly",
    "quickly",
    "rapidly",
    "fast",
    "well",
    "better",
    "best",
    "badly",
    "worse",
    "worst",
    "far",
    "near",
    "close",
    "away",
    "back",
    "forward",
    "ahead",
    "together",
    "apart",
    "alone",
    "otherwise",
    "instead",
    "anyway",
    "however",
    "therefore",
    "thus",
    "hence",
    "consequently",
    "accordingly",
    "meanwhile",
    "moreover",
    "furthermore",
    "nevertheless",
    "nonetheless",
    "regardless",
    "overall",
    "indeed",
    "apparently",
    // ========================================
    // ADJECTIVES (common forms)
    // ========================================
    "new",
    "old",
    "good",
    "bad",
    "great",
    "little",
    "big",
    "small",
    "large",
    "long",
    "short",
    "high",
    "low",
    "young",
    "best",
    "worst",
    "first",
    "last",
    "next",
    "same",
    "different",
    "other",
    "another",
    "own",
    "certain",
    "particular",
    "specific",
    "general",
    "main",
    "major",
    "important",
    "significant",
    "various",
    "several",
    "few",
    "many",
    "much",
    "more",
    "most",
    "less",
    "least",
    "enough",
    "such",
    "whole",
    "entire",
    "full",
    "empty",
    "true",
    "false",
    "right",
    "wrong",
    "real",
    "actual",
    "possible",
    "likely",
    "unlikely",
    "available",
    "necessary",
    "able",
    "unable",
    "similar",
    "different",
    "common",
    "recent",
    "current",
    "former",
    "latter",
    "previous",
    "following",
    "early",
    "late",
    "open",
    "closed",
    "public",
    "private",
    "free",
    "clear",
    "sure",
    "ready",
    "hard",
    "easy",
    // ========================================
    // NUMBERS
    // ========================================
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "hundred",
    "thousand",
    "million",
    "billion",
    "first",
    "second",
    "third",
    "fourth",
    "fifth",
    "sixth",
    "seventh",
    "eighth",
    "ninth",
    "tenth",
    "once",
    "twice",
    // ========================================
    // TIME-RELATED
    // ========================================
    "time",
    "times",
    "day",
    "days",
    "week",
    "weeks",
    "month",
    "months",
    "year",
    "years",
    "hour",
    "hours",
    "minute",
    "minutes",
    "second",
    "seconds",
    "today",
    "yesterday",
    "tomorrow",
    "tonight",
    "morning",
    "afternoon",
    "evening",
    "night",
    "now",
    "then",
    "ago",
    "later",
    "soon",
    "early",
    "late",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "spring",
    "summer",
    "autumn",
    "fall",
    "winter",
    // ========================================
    // GENERIC NOUNS
    // ========================================
    "way",
    "ways",
    "thing",
    "things",
    "case",
    "cases",
    "fact",
    "facts",
    "point",
    "points",
    "part",
    "parts",
    "place",
    "places",
    "side",
    "sides",
    "end",
    "ends",
    "start",
    "beginning",
    "middle",
    "person",
    "people",
    "man",
    "men",
    "woman",
    "women",
    "child",
    "children",
    "world",
    "life",
    "lives",
    "hand",
    "hands",
    "work",
    "works",
    "number",
    "numbers",
    "group",
    "groups",
    "area",
    "areas",
    "problem",
    "problems",
    "question",
    "questions",
    "issue",
    "issues",
    "reason",
    "reasons",
    "result",
    "results",
    "example",
    "examples",
    "kind",
    "kinds",
    "type",
    "types",
    "sort",
    "sorts",
    "form",
    "forms",
    "level",
    "levels",
    "state",
    "states",
    "situation",
    "situations",
    "matter",
    "matters",
    "idea",
    "ideas",
    "view",
    "views",
    "opinion",
    "opinions",
    // ========================================
    // WEB/ARTICLE COMMON WORDS
    // ========================================
    "article",
    "articles",
    "page",
    "pages",
    "read",
    "more",
    "click",
    "here",
    "share",
    "comment",
    "comments",
    "subscribe",
    "newsletter",
    "follow",
    "link",
    "links",
    "source",
    "sources",
    "photo",
    "photos",
    "image",
    "images",
    "video",
    "videos",
    "content",
    "contents",
    "post",
    "posts",
    "breaking",
    "exclusive",
    "update",
    "updates",
    "latest",
    "trending",
    "featured",
    "popular",
    "top",
    "best",
    "new",
    "related",
    // ========================================
    // TECHNICAL/WEB FRAGMENTS
    // ========================================
    "path",
    "file",
    "data",
    "type",
    "name",
    "value",
    "key",
    "item",
    "items",
    "list",
    "view",
    "show",
    "hide",
    "open",
    "close",
    "add",
    "remove",
    "delete",
    "edit",
    "update",
    "create",
    "set",
    "get",
    "put",
    "post",
    "send",
    "receive",
    "true",
    "false",
    "null",
    "undefined",
    "error",
    "success",
    "failed",
];

/// HTML tags, attributes, and web-related technical terms
static HTML_STOPWORDS: &[&str] = &[
    // HTML tags
    "html",
    "head",
    "body",
    "div",
    "span",
    "p",
    "br",
    "hr",
    "img",
    "a",
    "ul",
    "ol",
    "li",
    "table",
    "tr",
    "td",
    "th",
    "thead",
    "tbody",
    "tfoot",
    "form",
    "input",
    "button",
    "label",
    "select",
    "option",
    "textarea",
    "header",
    "footer",
    "nav",
    "aside",
    "section",
    "article",
    "main",
    "figure",
    "figcaption",
    "video",
    "audio",
    "iframe",
    "canvas",
    "svg",
    "script",
    "style",
    "link",
    "meta",
    "title",
    "noscript",
    "embed",
    "object",
    "param",
    "source",
    "track",
    "picture",
    "map",
    "area",
    "blockquote",
    "pre",
    "code",
    "em",
    "strong",
    "small",
    "sub",
    "sup",
    "mark",
    "del",
    "ins",
    "abbr",
    "cite",
    "dfn",
    "kbd",
    "samp",
    "var",
    "wbr",
    "details",
    "summary",
    "dialog",
    "menu",
    "menuitem",
    "template",
    "slot",
    "fieldset",
    "legend",
    "datalist",
    "output",
    "progress",
    "meter",
    "ruby",
    "rt",
    "rp",
    "bdi",
    "bdo",
    "col",
    "colgroup",
    "caption",
    "optgroup",
    "address",
    "time",
    "data",
    // HTML attributes
    "href",
    "src",
    "alt",
    "class",
    "id",
    "name",
    "type",
    "value",
    "placeholder",
    "action",
    "method",
    "target",
    "rel",
    "title",
    "style",
    "onclick",
    "onload",
    "onchange",
    "onsubmit",
    "onmouseover",
    "onmouseout",
    "onfocus",
    "onblur",
    "disabled",
    "readonly",
    "required",
    "checked",
    "selected",
    "multiple",
    "autofocus",
    "autocomplete",
    "maxlength",
    "minlength",
    "pattern",
    "min",
    "max",
    "step",
    "cols",
    "rows",
    "wrap",
    "width",
    "height",
    "size",
    "accept",
    "charset",
    "content",
    "http",
    "equiv",
    "async",
    "defer",
    "crossorigin",
    "integrity",
    "loading",
    "decoding",
    "srcset",
    "sizes",
    "media",
    "preload",
    "autoplay",
    "controls",
    "loop",
    "muted",
    "poster",
    "datetime",
    "download",
    "hreflang",
    "ping",
    "referrerpolicy",
    "sandbox",
    "allow",
    "allowfullscreen",
    "frameborder",
    "scrolling",
    "marginwidth",
    "marginheight",
    "xmlns",
    "lang",
    "dir",
    "tabindex",
    "accesskey",
    "draggable",
    "contenteditable",
    "spellcheck",
    "translate",
    "hidden",
    "role",
    "aria",
    "data",
    "slot",
    "part",
    "exportparts",
    "is",
    // HTML entities (decoded)
    "nbsp",
    "quot",
    "amp",
    "lt",
    "gt",
    "apos",
    "copy",
    "reg",
    "trade",
    "euro",
    "pound",
    "yen",
    "cent",
    "sect",
    "deg",
    "plusmn",
    "times",
    "divide",
    "frac",
    "mdash",
    "ndash",
    "lsquo",
    "rsquo",
    "ldquo",
    "rdquo",
    "bull",
    "hellip",
    // CSS properties and values
    "px",
    "em",
    "rem",
    "vh",
    "vw",
    "vmin",
    "vmax",
    "ch",
    "ex",
    "pt",
    "pc",
    "cm",
    "mm",
    "auto",
    "none",
    "inherit",
    "initial",
    "unset",
    "revert",
    "block",
    "inline",
    "flex",
    "grid",
    "absolute",
    "relative",
    "fixed",
    "sticky",
    "static",
    "margin",
    "padding",
    "border",
    "outline",
    "background",
    "color",
    "font",
    "display",
    "position",
    "float",
    "clear",
    "overflow",
    "visibility",
    "opacity",
    "transform",
    "transition",
    "animation",
    "cursor",
    "pointer",
    "text",
    "align",
    "vertical",
    "horizontal",
    "top",
    "bottom",
    "left",
    "right",
    "center",
    "middle",
    "justify",
    "stretch",
    "wrap",
    "nowrap",
    "row",
    "column",
    "reverse",
    "space",
    "between",
    "around",
    "evenly",
    "start",
    "end",
    "baseline",
    "content",
    "items",
    "self",
    "order",
    "grow",
    "shrink",
    "basis",
    "gap",
    "template",
    "repeat",
    "minmax",
    "fit",
    "fill",
    "span",
    "dense",
    "rgb",
    "rgba",
    "hsl",
    "hsla",
    "hex",
    "transparent",
    "currentcolor",
    "solid",
    "dashed",
    "dotted",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "collapse",
    "separate",
    "hidden",
    "visible",
    "scroll",
    "clip",
    "ellipsis",
    "break",
    "word",
    "normal",
    "pre",
    "bold",
    "italic",
    "underline",
    "overline",
    "line",
    "through",
    "capitalize",
    "uppercase",
    "lowercase",
    "serif",
    "sans",
    "monospace",
    "cursive",
    "fantasy",
    "system",
    "ui",
    "emoji",
    "math",
    // URL and protocol related
    "https",
    "http",
    "ftp",
    "mailto",
    "tel",
    "javascript",
    "data",
    "blob",
    "file",
    "www",
    "com",
    "org",
    "net",
    "de",
    "edu",
    "gov",
    "io",
    "co",
    "uk",
    "eu",
    "info",
    "html",
    "htm",
    "php",
    "asp",
    "aspx",
    "jsp",
    "cgi",
    "xml",
    "json",
    "css",
    "js",
    "png",
    "jpg",
    "jpeg",
    "gif",
    "svg",
    "webp",
    "ico",
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    "zip",
    "rar",
    "tar",
    "gz",
    "mp3",
    "mp4",
    "avi",
    "mov",
    "webm",
    "ogg",
    "wav",
    "flac",
    "ttf",
    "otf",
    "woff",
    "woff2",
    "eot",
    // Common web/technical abbreviations
    "url",
    "uri",
    "api",
    "cdn",
    "dns",
    "ssl",
    "tls",
    "dom",
    "ajax",
    "xhr",
    "cors",
    "jwt",
    "oauth",
    "sso",
    "cms",
    "crm",
    "erp",
    "saas",
    "paas",
    "iaas",
    "vpc",
    "sdk",
    "cli",
    "gui",
    "ide",
    "sql",
    "nosql",
    "crud",
    "rest",
    "soap",
    "graphql",
    "rpc",
    "tcp",
    "udp",
    "ip",
    "mac",
    "lan",
    "wan",
    "vpn",
    "ssh",
    "sftp",
    "smtp",
    "imap",
    "pop",
    "rss",
    "atom",
    "opml",
    "ical",
    "vcf",
    "csv",
    "tsv",
    "yaml",
    "toml",
    "ini",
    // JavaScript/programming related
    "var",
    "let",
    "const",
    "function",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "break",
    "continue",
    "try",
    "catch",
    "finally",
    "throw",
    "new",
    "this",
    "class",
    "extends",
    "super",
    "static",
    "get",
    "set",
    "async",
    "await",
    "import",
    "export",
    "default",
    "from",
    "module",
    "require",
    "define",
    "typeof",
    "instanceof",
    "null",
    "undefined",
    "true",
    "false",
    "nan",
    "infinity",
    "console",
    "log",
    "error",
    "warn",
    "info",
    "debug",
    "alert",
    "confirm",
    "prompt",
    "window",
    "document",
    "element",
    "node",
    "event",
    "listener",
    "handler",
    "callback",
    "promise",
    "then",
    "resolve",
    "reject",
    "fetch",
    "response",
    "request",
    "object",
    "array",
    "string",
    "number",
    "boolean",
    "symbol",
    "map",
    "set",
    "date",
    "regexp",
    "math",
    "json",
    "parse",
    "stringify",
    "encode",
    "decode",
    "buffer",
    // Common tracking/analytics terms
    "tracking",
    "analytics",
    "pixel",
    "beacon",
    "tag",
    "gtm",
    "ga",
    "utm",
    "source",
    "medium",
    "campaign",
    "term",
    "cookie",
    "session",
    "storage",
    "local",
    "cache",
];

/// News-specific stopwords (journalistic terms, generic filler)
/// NOTE: Media outlet names (BBC, CNN, Reuters, etc.) are loaded from resources/stopwords/news.txt
/// into the database. This static list contains generic news language only.
static NEWS_STOPWORDS: &[&str] = &[
    // === German News Terms ===
    "bericht",
    "laut",
    "unterdessen",
    "video",
    "update",
    "interview",
    "kommentar",
    "mehr",
    "neue",
    "ersten",
    "lesen",
    "artikel",
    "news",
    "uhr",
    "foto",
    "quelle",
    "aktualisiert",
    "redaktion",
    "meldung",
    "nachricht",
    "pressemitteilung",
    "mitteilung",
    "stellungnahme",
    // German generic news filler
    "beitrag",
    "eilmeldung",
    "liveticker",
    "zur",
    "beim",
    "vom",
    "zum",
    // === English News Terms ===
    "according",
    "comment",
    "read",
    "article",
    "source",
    "photo",
    "breaking",
    "exclusive",
    "update",
    "live",
    "developing",
    "correspondent",
    "reporter",
    "editor",
    "editorial",
    "opinion",
    "analysis",
    "wire",
    "featured",
    "trending",
    "viral",
    "latest",
    // === Generic Article/Content Terms ===
    "weiterlesen",
    "mehr lesen",
    "read more",
    "continue reading",
    "abonnieren",
    "subscribe",
    "newsletter",
    "rss feed",
    "teilen",
    "share",
    "tweet",
    "facebook",
    "twitter",
    "linkedin",
    "kommentare",
    "comments",
    "diskussion",
    "discussion",
    "anzeige",
    "werbung",
    "sponsored",
    "ad",
    "advertisement",
    "premium",
    "plus",
    "abo",
    "paywall",
    // === Attribution markers (but not the outlet names themselves) ===
    "exklusiv",
    "breaking news",
    "eilmeldung",
    "liveticker",
    "aktualisiert am",
    "stand",
    "veröffentlicht",
    "published",
];

// ============================================================
// DATABASE STOPWORDS (System + User)
// ============================================================

/// Load all stopwords from database (system + user)
pub fn load_all_db_stopwords(conn: &Connection) -> Result<HashSet<String>, rusqlite::Error> {
    let mut stmt = conn.prepare("SELECT word FROM stopwords")?;
    let rows = stmt.query_map([], |row| row.get::<_, String>(0))?;

    let mut words = HashSet::new();
    for row in rows {
        words.insert(row?.to_lowercase());
    }
    Ok(words)
}

/// Load user-defined stopwords from database (for backwards compatibility)
pub fn load_user_stopwords(conn: &Connection) -> Result<HashSet<String>, rusqlite::Error> {
    let mut stmt = conn.prepare("SELECT word FROM stopwords WHERE source = 'user'")?;
    let rows = stmt.query_map([], |row| row.get::<_, String>(0))?;

    let mut words = HashSet::new();
    for row in rows {
        words.insert(row?.to_lowercase());
    }
    Ok(words)
}

/// Load system stopwords from database
#[allow(dead_code)] // Public API for loading system-defined stopwords
pub fn load_system_stopwords(conn: &Connection) -> Result<HashSet<String>, rusqlite::Error> {
    let mut stmt = conn.prepare("SELECT word FROM stopwords WHERE source = 'system'")?;
    let rows = stmt.query_map([], |row| row.get::<_, String>(0))?;

    let mut words = HashSet::new();
    for row in rows {
        words.insert(row?.to_lowercase());
    }
    Ok(words)
}

/// Add a user stopword to the database
pub fn add_user_stopword(conn: &Connection, word: &str) -> Result<(), rusqlite::Error> {
    let word_lower = word.trim().to_lowercase();
    if word_lower.is_empty() {
        return Ok(());
    }
    conn.execute(
        "INSERT OR IGNORE INTO stopwords (word, source) VALUES (?, 'user')",
        [&word_lower],
    )?;
    Ok(())
}

/// Remove a user stopword from the database (only removes user-added stopwords)
pub fn remove_user_stopword(conn: &Connection, word: &str) -> Result<bool, rusqlite::Error> {
    let word_lower = word.trim().to_lowercase();
    let deleted = conn.execute(
        "DELETE FROM stopwords WHERE LOWER(word) = ? AND source = 'user'",
        [&word_lower],
    )?;
    Ok(deleted > 0)
}

/// Remove any stopword from the database (system or user)
#[allow(dead_code)] // Public API for stopword management
pub fn remove_stopword(conn: &Connection, word: &str) -> Result<bool, rusqlite::Error> {
    let word_lower = word.trim().to_lowercase();
    let deleted = conn.execute("DELETE FROM stopwords WHERE LOWER(word) = ?", [&word_lower])?;
    Ok(deleted > 0)
}

/// Get count of user stopwords
pub fn count_user_stopwords(conn: &Connection) -> Result<i64, rusqlite::Error> {
    conn.query_row(
        "SELECT COUNT(*) FROM stopwords WHERE source = 'user'",
        [],
        |row| row.get(0),
    )
}

/// Get count of system stopwords
pub fn count_system_stopwords(conn: &Connection) -> Result<i64, rusqlite::Error> {
    conn.query_row(
        "SELECT COUNT(*) FROM stopwords WHERE source = 'system'",
        [],
        |row| row.get(0),
    )
}

/// Get count of all stopwords in database
#[allow(dead_code)] // Public API for stopword statistics
pub fn count_all_stopwords(conn: &Connection) -> Result<i64, rusqlite::Error> {
    conn.query_row("SELECT COUNT(*) FROM stopwords", [], |row| row.get(0))
}

/// Check if a word is a stopword (database + static fallback)
#[allow(dead_code)] // Public API for stopword checking
pub fn is_stopword(word: &str, db_stopwords: Option<&HashSet<String>>) -> bool {
    let lower = word.to_lowercase();

    // Check provided database stopwords first
    if let Some(db) = db_stopwords {
        if db.contains(&lower) {
            return true;
        }
    }

    // Fallback to static stopwords if no DB stopwords provided
    if db_stopwords.is_none() && STOPWORDS.contains(lower.as_str()) {
        return true;
    }

    false
}

/// Get all stopwords (database-first, static fallback)
#[allow(dead_code)] // Public API for stopword retrieval
pub fn get_all_stopwords(conn: &Connection) -> HashSet<String> {
    // Try to load from database first
    if let Ok(db_stopwords) = load_all_db_stopwords(conn) {
        if !db_stopwords.is_empty() {
            return db_stopwords;
        }
    }

    // Fallback to static stopwords
    STOPWORDS.iter().map(|s| s.to_string()).collect()
}

/// Get statistics about stopwords
pub struct StopwordStats {
    pub system_count: i64,
    pub user_count: i64,
    pub builtin_count: usize,
    pub total_count: i64,
}

pub fn get_stopword_stats(conn: &Connection) -> Result<StopwordStats, rusqlite::Error> {
    let system_count = count_system_stopwords(conn)?;
    let user_count = count_user_stopwords(conn)?;
    let builtin_count = STOPWORDS.len();
    let total_count = system_count + user_count;

    Ok(StopwordStats {
        system_count,
        user_count,
        builtin_count,
        total_count,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stopwords_contains_common_words() {
        assert!(STOPWORDS.contains("der"));
        assert!(STOPWORDS.contains("die"));
        assert!(STOPWORDS.contains("the"));
        assert!(STOPWORDS.contains("and"));
    }

    #[test]
    fn test_stopwords_contains_html_terms() {
        assert!(STOPWORDS.contains("https"));
        assert!(STOPWORDS.contains("href"));
        assert!(STOPWORDS.contains("figcaption"));
        assert!(STOPWORDS.contains("span"));
        assert!(STOPWORDS.contains("quot"));
        assert!(STOPWORDS.contains("div"));
        assert!(STOPWORDS.contains("onclick"));
    }

    #[test]
    fn test_stopwords_does_not_contain_content_words() {
        assert!(!STOPWORDS.contains("politik"));
        assert!(!STOPWORDS.contains("technology"));
        assert!(!STOPWORDS.contains("wirtschaft"));
    }

    #[test]
    fn test_media_outlets_are_stopwords_in_db() {
        // Media outlets ARE stopwords (loaded from news.txt into database)
        // They appear as keywords due to attribution, not because they're actual topics
        // Note: Static STOPWORDS doesn't include them - they're in the database stopwords
        // The database-loaded stopwords from news.txt contain: bbc, cnn, reuters, dpa, etc.
        // This test verifies the static list behavior (unchanged from builtin)
        assert!(!STOPWORDS.contains("bbc")); // Not in static, but in DB via news.txt
    }

    #[test]
    fn test_stopwords_contains_generic_news_terms() {
        // Generic news filler terms should be filtered
        assert!(STOPWORDS.contains("beitrag"));
        assert!(STOPWORDS.contains("eilmeldung"));
        assert!(STOPWORDS.contains("liveticker"));
        assert!(STOPWORDS.contains("weiterlesen"));
        assert!(STOPWORDS.contains("newsletter"));
    }
}
