//! Unified keyword types for the fuckupRSS application
//!
//! This module provides a central definition of keyword-related types
//! to ensure consistency across the codebase.

use serde::{Deserialize, Serialize};

/// Source of a keyword - indicates how it was generated
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum KeywordSource {
    /// Generated by AI/LLM (Discordian Analysis)
    #[default]
    Ai,
    /// Generated by statistical analysis (TF-IDF)
    Statistical,
    /// Added manually by user
    Manual,
}

impl std::fmt::Display for KeywordSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Ai => write!(f, "ai"),
            Self::Statistical => write!(f, "statistical"),
            Self::Manual => write!(f, "manual"),
        }
    }
}

impl From<&str> for KeywordSource {
    fn from(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "ai" => Self::Ai,
            "statistical" | "stat" => Self::Statistical,
            "manual" | "user" => Self::Manual,
            _ => Self::Ai,
        }
    }
}

impl From<String> for KeywordSource {
    fn from(s: String) -> Self {
        Self::from(s.as_str())
    }
}

/// A keyword candidate from extraction (TF-IDF or other statistical methods)
///
/// Used during the extraction phase before keywords are saved to the database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtractedKeywordCandidate {
    /// The keyword term (may be normalized)
    pub term: String,
    /// Relevance score (TF-IDF score, higher = more relevant)
    pub score: f64,
    /// Raw frequency in the document
    pub frequency: u32,
    /// Source of extraction
    pub source: KeywordSource,
}

impl ExtractedKeywordCandidate {
    /// Create a new keyword candidate with default source
    pub fn new(term: String, score: f64, frequency: u32) -> Self {
        Self {
            term,
            score,
            frequency,
            source: KeywordSource::Statistical,
        }
    }

    /// Create from TF-IDF extraction
    pub fn from_tfidf(term: String, score: f64, frequency: u32) -> Self {
        Self {
            term,
            score,
            frequency,
            source: KeywordSource::Statistical,
        }
    }

    /// Create from AI/LLM extraction
    pub fn from_ai(term: String, score: f64) -> Self {
        Self {
            term,
            score,
            frequency: 0,
            source: KeywordSource::Ai,
        }
    }
}

/// A keyword associated with an article (stored in fnord_immanentize)
///
/// Represents the relationship between an article and a keyword,
/// including metadata about how and when it was assigned.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArticleKeywordRef {
    /// Database ID of the keyword (from immanentize table)
    pub id: i64,
    /// The keyword name
    pub name: String,
    /// How this keyword was assigned
    pub source: KeywordSource,
    /// Confidence score (0.0 - 1.0)
    pub confidence: f64,
}

impl ArticleKeywordRef {
    /// Create a new article keyword reference
    pub fn new(id: i64, name: String, source: KeywordSource, confidence: f64) -> Self {
        Self {
            id,
            name,
            source,
            confidence,
        }
    }

    /// Create from string source (for backward compatibility)
    pub fn from_string_source(id: i64, name: String, source: &str, confidence: f64) -> Self {
        Self {
            id,
            name,
            source: KeywordSource::from(source),
            confidence,
        }
    }
}

/// A keyword with source tracking (before database ID is known)
///
/// Used during processing when we know the keyword name and source
/// but haven't yet looked up or created the database record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeywordWithMetadata {
    /// The keyword name
    pub name: String,
    /// How this keyword was generated
    pub source: KeywordSource,
    /// Confidence score (0.0 - 1.0)
    pub confidence: f64,
    /// Type of keyword (concept, person, organization, location, acronym)
    #[serde(default = "default_keyword_type")]
    pub keyword_type: String,
}

fn default_keyword_type() -> String {
    "concept".to_string()
}

impl KeywordWithMetadata {
    /// Create a new keyword with metadata
    pub fn new(name: String, source: KeywordSource, confidence: f64) -> Self {
        Self {
            name,
            source,
            confidence,
            keyword_type: "concept".to_string(),
        }
    }

    /// Create a new keyword with metadata and type
    pub fn new_with_type(
        name: String,
        source: KeywordSource,
        confidence: f64,
        keyword_type: String,
    ) -> Self {
        Self {
            name,
            source,
            confidence,
            keyword_type,
        }
    }

    /// Create from AI source with full confidence
    pub fn from_ai(name: String) -> Self {
        Self {
            name,
            source: KeywordSource::Ai,
            confidence: 1.0,
            keyword_type: "concept".to_string(),
        }
    }

    /// Create from AI source with type
    pub fn from_ai_with_type(name: String, keyword_type: String) -> Self {
        Self {
            name,
            source: KeywordSource::Ai,
            confidence: 1.0,
            keyword_type,
        }
    }

    /// Create from statistical source
    pub fn from_statistical(name: String, confidence: f64) -> Self {
        Self {
            name,
            source: KeywordSource::Statistical,
            confidence,
            keyword_type: "concept".to_string(),
        }
    }

    /// Create from manual/user input
    pub fn from_manual(name: String) -> Self {
        Self {
            name,
            source: KeywordSource::Manual,
            confidence: 1.0,
            keyword_type: "concept".to_string(),
        }
    }

    /// Get source as string for database storage
    pub fn source_str(&self) -> &'static str {
        match self.source {
            KeywordSource::Ai => "ai",
            KeywordSource::Statistical => "statistical",
            KeywordSource::Manual => "manual",
        }
    }
}

/// Conversion from old `KeywordWithSource` format (string-based source)
impl From<(String, String, f64)> for KeywordWithMetadata {
    fn from((name, source, confidence): (String, String, f64)) -> Self {
        Self {
            name,
            source: KeywordSource::from(source),
            confidence,
            keyword_type: "concept".to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keyword_source_from_str() {
        assert_eq!(KeywordSource::from("ai"), KeywordSource::Ai);
        assert_eq!(
            KeywordSource::from("statistical"),
            KeywordSource::Statistical
        );
        assert_eq!(KeywordSource::from("stat"), KeywordSource::Statistical);
        assert_eq!(KeywordSource::from("manual"), KeywordSource::Manual);
        assert_eq!(KeywordSource::from("user"), KeywordSource::Manual);
        assert_eq!(KeywordSource::from("unknown"), KeywordSource::Ai);
    }

    #[test]
    fn test_keyword_source_display() {
        assert_eq!(format!("{}", KeywordSource::Ai), "ai");
        assert_eq!(format!("{}", KeywordSource::Statistical), "statistical");
        assert_eq!(format!("{}", KeywordSource::Manual), "manual");
    }

    #[test]
    fn test_keyword_with_metadata() {
        let kw = KeywordWithMetadata::from_ai("Test".to_string());
        assert_eq!(kw.source, KeywordSource::Ai);
        assert_eq!(kw.confidence, 1.0);
        assert_eq!(kw.source_str(), "ai");

        let kw = KeywordWithMetadata::from_statistical("Test".to_string(), 0.8);
        assert_eq!(kw.source, KeywordSource::Statistical);
        assert_eq!(kw.confidence, 0.8);
    }

    #[test]
    fn test_extracted_keyword_candidate() {
        let kw = ExtractedKeywordCandidate::from_tfidf("Test".to_string(), 0.5, 3);
        assert_eq!(kw.term, "Test");
        assert_eq!(kw.score, 0.5);
        assert_eq!(kw.frequency, 3);
        assert_eq!(kw.source, KeywordSource::Statistical);
    }
}
